name: Data Processing Workflow

on:
  push:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:

          python-version: '3.13'
      - name: Run split_data.py script
        run: python scripts/split_data.py

      - name: Upload output names.csv
        uses: actions/upload-artifact@v4
        with:
          name: copy-names
          path: data/names.csv

      - name: Upload output places.csv
        uses: actions/upload-artifact@v4
        with:
          name: copy-places
          path: data/places.csv